name: Deploy
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependency
        run: yarn install
        shell: bash
      - name: Build
        run: yarn run docs:build
        shell: bash
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          user: ${{ secrets.HOSTINGER_USERNAME }}
          pass: ${{ secrets.HOSTINGER_PASSWORD }}
          port: ${{ secrets.HOSTINGER_PORT }}
          scp: |
            './docs/.vitepress/dist/*' => /home/u835893703/domains/fullstackbd.com/public_html/docs/

      